# Generated by Django 6.0.6 on 2026-09-29 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/leadership/')),
            ],
            options={
                'verbose_name': 'Leader',
                'verbose_name_plural': 'Leadership',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/pillars/')),
            ],
            options={
                'verbose_name': 'Pillar',
                'verbose_name_plural': 'Pillars',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/team/')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('hero_title_highlight', models.CharField(blank=True, max_length=255)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('intro_paragraphs', models.TextField(blank=True, help_text='Rich text. Wrap each paragraph in its own <p> tag.')),
                ('show_intro', models.BooleanField(default=True)),
                ('commitment_title', models.CharField(blank=True, max_length=255)),
                ('commitment_text', models.TextField(blank=True)),
                ('show_commitment', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('achievements_title', models.CharField(blank=True, max_length=255)),
                ('achievements_paragraphs', models.TextField(blank=True, help_text='Rich text shown under the achievement stats.')),
                ('show_leadership', models.BooleanField(default=True)),
                ('leadership_title', models.CharField(blank=True, max_length=255)),
                ('leadership_subtitle', models.TextField(blank=True)),
                ('show_pillars', models.BooleanField(default=True)),
                ('pillars_title', models.CharField(blank=True, max_length=255)),
                ('show_team', models.BooleanField(default=True)),
                ('team_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
    ]
