# Generated by Django 6.0.6 on 2026-08-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training/'),
        ),
    ]
