# Generated by Django 6.0.6 on 2026-07-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_company_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('jobseeker', 'Job Seeker')], default='employee', max_length=20),
        ),
    ]
