# Generated by Django 6.0.6 on 2026-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_special_account',
            field=models.BooleanField(default=False, help_text="Grants unlimited access without changing the user's original role."),
        ),
    ]
