# Generated by Django 6.0.6 on 2026-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_auth_provider_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_token_expires',
            new_name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
