# Generated by Django 6.0.6 on 2026-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/certificates/'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='citizenship_copy',
            field=models.FileField(blank=True, null=True, upload_to='job_applications/citizenship/'),
        ),
    ]
