# Generated by Django 6.0.6 on 2026-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_jobapplication_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
