# Generated by Django 6.0.6 on 2026-08-12 08:39

import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_jobapplication_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='certificates',
            field=models.FileField(blank=True, null=True, storage=backend.storage.get_raw_storage, upload_to='job_applications/certificates/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='citizenship_copy',
            field=models.FileField(blank=True, null=True, storage=backend.storage.get_raw_storage, upload_to='job_applications/citizenship/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=backend.storage.get_raw_storage, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=backend.storage.get_raw_storage, upload_to='resumes/'),
        ),
    ]
