# Generated by Django 6.0.6 on 2026-10-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0010_alter_jobapplication_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
